name: CI

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  pythonlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "./src/server"
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: true
          use-mypy: false
          use-isort: false
          extra-flake8-options: "--config=./src/server/setup.cfg"
  jslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/client
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESlint
        run: yarn run eslint --ext .js,.jsx,.ts,.tsx
