name: CI

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  pythonlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ricardochaves/python-lint@v1.3.0
        with:
          python-root-list: "./src/server"
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: true
          use-mypy: false
          use-isort: true
          extra-flake8-options: "--config=./src/server/setup.cfg"
  jslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESlint
        run: yarn run eslint ./src/client --config ./src/client/.eslintrc.js --ext .js,.jsx,.ts,.tsx
